### ISSUE TITLE
Downloading Murao showcase data leads to "accessdenied" XML

### ISSUE THREAD

**Issue by ConnectedSystems** [GFDRR/riskdatalibrary.org#88]
Steps to reproduce:

1. Navigate to Vulnerability datasets [here](http://riskdatalibrary.org/data)
2. Click on the download icon next to/in License column
3. Select CSV or JSON

User will then be taken to page filled with XML, something similar to:

```XML
<Error>
<Code>AccessDenied</Code>
<Message>Request has expired</Message>
<X-Amz-Expires>3600</X-Amz-Expires>
<Expires>2020-11-24T11:15:09Z</Expires>
<ServerTime>2020-11-24T12:48:40Z</ServerTime>
<RequestId>E2632C0AE26DCCB1</RequestId>
<HostId>Y1M1R03ElcUj82a+h4fwMjWHrYDtG5PMQxgfSz9ZVTYJvn+2DyEkA9F+o0wpUI7M9OLp4sTPdQs=</HostId>
</Error>
```

Strangely, downloading from the [data details page](http://riskdatalibrary.org/data-details#vulnerability=20) appears to work

**Comment by MamadioCMCC** [comment]
Yes, had this issue as well. If you let the page open too long, then the download fail with this error.
No idea why it happens.

**Comment by ConnectedSystems** [comment]
Just double checked this and it seems to be working again. Let's keep an eye on it.

**Comment by ConnectedSystems** [comment]
Closing as it seems to have resolved itself.
